In [11]:
import pandas as pd
import numpy as np

df3 = pd.read_excel("./DataScience-master/data/01_population_in_Seoul.xls", header=2)

In [12]:
df4 = df3.loc[:,['자치구','계','계.1','계.2','65세이상고령자']]
df5 = df4.rename(columns = {'자치구': '구별',
                    '계' : '인구수',
                    '계.1' : '한국인',
                    '계.2' : '외국인',
                    '65세이상고령자' : '고령자'})
df5.head()
df5

      구별         인구수        한국인       외국인        고령자
0     합계  10197604.0  9926968.0  270636.0  1321458.0
1    종로구    162820.0   153589.0    9231.0    25425.0
2     중구    133240.0   124312.0    8928.0    20764.0
3    용산구    244203.0   229456.0   14747.0    36231.0
4    성동구    311244.0   303380.0    7864.0    39997.0
5    광진구    372164.0   357211.0   14953.0    42214.0
6   동대문구    369496.0   354079.0   15417.0    54173.0
7    중랑구    414503.0   409882.0    4621.0    56774.0
8    성북구    461260.0   449773.0   11487.0    64692.0
9    강북구    330192.0   326686.0    3506.0    54813.0
10   도봉구    348646.0   346629.0    2017.0    51312.0
11   노원구    569384.0   565565.0    3819.0    71941.0
12   은평구    494388.0   489943.0    4445.0    72334.0
13  서대문구    327163.0   314982.0   12181.0    48161.0
14   마포구    389649.0   378566.0   11083.0    48765.0
15   양천구    479978.0   475949.0    4029.0    52975.0
16   강서구    603772.0   597248.0    6524.0    72548.0
17   구로구    447874.0   416487.0   31387.0    56833.0
18   금천구    255082.0   236353.0   18729.0    32970.0
19  영등포구    402985.0   368072.0   34913.0    52413.0
20   동작구    412520.0   400456.0   12064.0    56013.0
21   관악구    525515.0   507203.0   18312.0    68082.0
22   서초구    450310.0   445994.0    4316.0    51733.0
23   강남구    570500.0   565550.0    4950.0    63167.0
24   송파구    667483.0   660584.0    6899.0    72506.0
25   강동구    453233.0   449019.0    4214.0    54622.0
26   NaN         NaN        NaN       NaN        NaN